server:
  servlet:
    context-path: /playing-spring
spring:
  main:
    web-application-type: servlet
  mvc:
    servlet:
      load-on-startup: 0
list:
  - a
  - b
  - c
  
map:
  k1: v1
  k2: v2
  k3: v3


list-list:
  - - a
    - b
  - - c
    - d
  - - e
    - f
    
list-map:
  - k1: v1
    k2: v2
  - k3: v3
    k4: v4
  - k5: v5
    k6: v6


map-map:
  k1:
    k11: v11
    k12: v12
  k2:
    k21: v21
    k22: v22
  k3:
    k31: v31
    k32: v32
    
map-list:
  k1:
    - a
    - b
  k2:
    - c
    - d
  k3:
    - e
    - f

swimming:
  scores:
    - level: 一等奖
      low-bound: 90
      high-bound: 100
    - level: 二等奖
      low-bound: 80
      high-bound: 90
    - level: 三等奖
      low-bound: 70
      high-bound: 80
  awards:
    level1:
      - name: 手机
        count: 1
      - name: 电脑
        count: 1
    level2:
      - name: 篮球
        count: 2
      - name: 足球
        count: 2
    level3:
      - name: 书包
        count: 3
      - name: 玩具
        count: 3

studying:
  computer: 1024

logging:
  level: 
    org.springframework.boot.autoconfigure: debug
    org.springframework.web.servlet: debug 